# Generated by Django 2.1.3 on 2018-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10)),
                ('numero_matricula', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=25)),
                ('nombres', models.CharField(max_length=25)),
                ('proveniencia', models.CharField(max_length=50)),
                ('carrera', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
