# Generated by Django 2.1.3 on 2018-11-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20181109_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='estado',
        ),
        migrations.AddField(
            model_name='usuario',
            name='trabaja',
            field=models.BooleanField(default=True),
        ),
    ]
